In [1]:
import torch

In [14]:
x = torch.ones(2, 2, requires_grad=True)    # requires_grad 可以对张量的运算进行跟踪
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
y = x + 2
print(y)    # y 作为操作的结果而生成，所以 y 具有 grad_fn
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [16]:
z = y * y * 3
out = z.mean()
print(z, out, sep='\n')

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [12]:
# tensor.requires_grad_(mode: bool = True) 可以更改一个 tensor 的 requires_grad，默认为 True 
a = torch.randn(2, 2)   # randn 是随机的，符合标准正态分布的生成函数
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [9]:
a = torch.rand(2, 2)
a.requires_grad_()
b = torch.randn(2, 2)
b.requires_grad_(False)
print(a.requires_grad, b.requires_grad, sep='\n')

True
False


In [17]:
out.backward()  # 由于 out 是标量，所以等价于 out.backward(torch.tensor(1.))
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


####对于上面得到的结果的解释：
你应该会得到一个全为 4.5 的矩阵。
让我们假设 `out` 张量是 "$o$"。我们计算得到 $o$ 的过程如下
$$
o=\frac{1}{4} \Sigma_i z_i, z_i=3(x_i+2)^2 \\ 
并且 \left. z_i \right |_{x_i=1}=27 \\
\therefore \frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2) \\
\therefore \left. \frac{\partial o}{\partial x_i} \right|_{x_i=1} = \frac{9}{2} = 4.5
$$

In [18]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 297.1255, 1047.5593,  659.4060], grad_fn=<MulBackward0>)


In [19]:
v = torch.tensor([0.1, 0.1, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+01, 5.1200e-02])
