介绍了 pytorch 的构建方法、加法、view 改变大小的方法、索引方法、item 取值

pytorch 张量的构建

In [1]:
import torch

In [2]:
import torchvision

In [3]:
print(torch)

<module 'torch' from 'f:\\anaconda\\lib\\site-packages\\torch\\__init__.py'>


In [4]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.2878, 0.7698, 0.6038],
        [0.7007, 0.9733, 0.0867],
        [0.3182, 0.8340, 0.5938],
        [0.6586, 0.6584, 0.4347],
        [0.4399, 0.9010, 0.2475]])


In [15]:
x = torch.empty(5, 3)   # 构造空矩阵 5x3，不初始化
print(x)
x = torch.rand(5, 3)    # 构造随机初始化的 5x3 矩阵
print(x)
x = torch.zeros(5, 3, dtype=torch.long) # 构造 5x3 矩阵，0 初始化，并自定义数据类型
print(x)
x = torch.tensor([5.5, 3])  # 直接使用数据构造张量
print(x)

tensor([[9.2755e-39, 1.0194e-38, 9.9184e-39],
        [7.8980e-39, 8.4490e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 1.0286e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39],
        [3.8572e-39, 3.8572e-39,        nan]])
tensor([[0.7411, 0.9281, 0.6263],
        [0.0299, 0.1560, 0.2303],
        [0.4472, 0.3257, 0.0084],
        [0.8446, 0.8001, 0.6145],
        [0.3392, 0.1423, 0.7590]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [14]:
from sys import getsizeof
print(getsizeof(x))
x = torch.zeros(5, 3, dtype=torch.int8)
print(getsizeof(x))

80
80


In [17]:
# 基于已存在的 tensor 创建一个 tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)  # 重载了 dtype
print(x) # 创建的结果具有和原先的 tensor 相同的 size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1804,  1.0565,  0.5775],
        [ 1.0293,  0.1222,  1.1320],
        [ 1.0361, -0.1865,  0.8912],
        [ 0.1746,  1.1628,  1.4601],
        [-0.4672, -0.7771, -1.2880]])
torch.Size([5, 3])


In [21]:
y = torch.rand(5, 3)
print(x+y)
print(torch.add(x, y))
# add 加法函数支持设置输出的目标
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
# 使用 tensor 对象的方法
y.add_(x)   # :y = y+x
print(y)

tensor([[ 0.1896,  1.5046,  0.9779],
        [ 1.6791,  0.5293,  1.9286],
        [ 1.7991, -0.0362,  1.7622],
        [ 0.8700,  1.3012,  2.2127],
        [ 0.1813, -0.1459, -0.3175]])
tensor([[ 0.1896,  1.5046,  0.9779],
        [ 1.6791,  0.5293,  1.9286],
        [ 1.7991, -0.0362,  1.7622],
        [ 0.8700,  1.3012,  2.2127],
        [ 0.1813, -0.1459, -0.3175]])
tensor([[ 0.1896,  1.5046,  0.9779],
        [ 1.6791,  0.5293,  1.9286],
        [ 1.7991, -0.0362,  1.7622],
        [ 0.8700,  1.3012,  2.2127],
        [ 0.1813, -0.1459, -0.3175]])
tensor([[ 0.1896,  1.5046,  0.9779],
        [ 1.6791,  0.5293,  1.9286],
        [ 1.7991, -0.0362,  1.7622],
        [ 0.8700,  1.3012,  2.2127],
        [ 0.1813, -0.1459, -0.3175]])


In [22]:
# tensor 支持类 numpy 的索引方式
print(x[:, 1])  
# x 的第二列，便于理解方式是，[列, 行]
# 样例中列取了全部，行取了第二个值，也就是所有行中的第二个值

tensor([ 1.0565,  0.1222, -0.1865,  1.1628, -0.7771])


In [23]:
# view 可以改变一个 tensor 的 size 和 shape
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # -1 表示根据其他维度的设置来自适应大小
# 样例中当设置 -1 列 8 行的情况，原本的 16 个数据会自动变成 2 列 8 行
# 当自适应的值不为一个整数的时候，会报错，比如 x.view(-1, 3) 
# RuntimeError: shape '[-1, 3]' is invalid for input of size 16
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
# 如果 tensor 只有一个元素的时候，可以使用 tensor.item() 来获取这个元素的值
x = torch.rand(1)
print(x.item())
# 当 tensor 不止一个元素的时候，会报错
# ValueError: only one element tensors can be converted to Python scalars

0.3582979440689087
