In [22]:
import torch
import torch.nn as nn
import torch.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(1, 1)
        self.tanh = nn.Tanh()
        self.predict = nn.Linear(1, 1)
    
    def forward(self, inputs):
        out = self.hidden(inputs)
        out = self.tanh(out)
        out = self.predict(out)
        return out

net = Net()
for i in net.parameters():
    print(i)
print(net(torch.tensor([1], dtype=torch.float32)))

Parameter containing:
tensor([[-0.7482]], requires_grad=True)
Parameter containing:
tensor([-0.6073], requires_grad=True)
Parameter containing:
tensor([[0.7169]], requires_grad=True)
Parameter containing:
tensor([-0.6757], requires_grad=True)
tensor([-0.6757], grad_fn=<AddBackward0>)


In [18]:
(-0.7482-0.6073)*0.7169

(-0.9969, -0.1876, -0.9298000000000001)

In [19]:
-0.9969*0.5119+0.1876*0.2116+0.3793*0.9298+0.4709

0.35295618999999995

In [20]:
t = nn.Linear(3, 1)
for i in t.parameters():
    print(i)
t(torch.tensor([1.5, 2.3, 1.7]))

Parameter containing:
tensor([[-0.0195,  0.5427,  0.1678]], requires_grad=True)
Parameter containing:
tensor([-0.5411], requires_grad=True)


tensor([0.9630], grad_fn=<AddBackward0>)

In [21]:
-0.0195*1.5+0.5427*2.3+0.1678*1.7-0.5411

0.9631199999999999